schema_version = "1.0.0"
id = "theme_ps"
name = "PS"
version = "1.0.2"
tagline = "Adobe Photoshop inspired light theme"
maintainer = "Oleksii Sereda <oleksiyartist@gmail.com>"
type = "theme"
tags = ["Inspired By", "Light"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
