schema_version = "1.0.0"

id = "Pastel_Pink_theme"
version = "0.0.3"
name = "Pastel_Pink"
tagline = "Bright and poppy pastel pink Blender theme by kame404"
maintainer = "kame404"
type = "theme"

website = "https://github.com/kame404/Blender-Themes"
tags = ["Light"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]